version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: webpulse-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-webpulse}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webpulse-network

  # Backend API
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: webpulse-server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-webpulse}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.example.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER:-your_email@example.com}
      EMAIL_PASS: ${EMAIL_PASS:-your_email_password}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@webpulse.com}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      LIGHTHOUSE_CHROME_PATH: /usr/bin/chromium-browser
      LIGHTHOUSE_DEFAULT_THROTTLING: ${LIGHTHOUSE_DEFAULT_THROTTLING:-true}
    volumes:
      - ./server/reports:/app/reports
    ports:
      - "5000:5000"
    networks:
      - webpulse-network

  # Frontend client
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: webpulse-client
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - webpulse-network

networks:
  webpulse-network:
    driver: bridge

volumes:
  postgres_data:
